import 'package:cached_network_image/cached_network_image.dart';
import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';

import '../../../core/constants/app_constants.dart';
import '../../../core/theme/app_colors.dart';
import '../../../core/theme/app_text_styles.dart';
import '../../../core/utils/profile_link.dart';
import 'share_profile_sheet.dart';

/// Scannable QR for the user's public profile (blueprint §16.11).
///
/// §16.11 flagged this as the lowest-confidence item and asked whether a real
/// QR feature exists on the web. It does: `ProfileShareModal.tsx` builds
/// `https://api.qrserver.com/v1/create-qr-code/?size=200x200&data=<url>` and
/// renders it as an image — the portal has no local QR renderer either.
/// Pointing at the same endpoint keeps both platforms identical and means no
/// QR package is needed on mobile.
void showProfileQrSheet(
  BuildContext context, {
  required String? userId,
  required String name,
  required String? userType,
}) {
  final shareUrl = profileShareUrl(
    userId: userId,
    name: name,
    role: userType,
  );

  showModalBottomSheet(
    context: context,
    backgroundColor: Colors.transparent,
    builder: (_) => _ProfileQrBody(shareUrl: shareUrl, name: name),
  );
}

class _ProfileQrBody extends StatelessWidget {
  final String shareUrl;
  final String name;

  const _ProfileQrBody({required this.shareUrl, required this.name});

  @override
  Widget build(BuildContext context) {
    return Container(
      decoration: const BoxDecoration(
        color: AppColors.cardBackground,
        borderRadius: BorderRadius.only(
          topLeft: Radius.circular(24),
          topRight: Radius.circular(24),
        ),
      ),
      padding: const EdgeInsets.fromLTRB(20, 10, 20, 20),
      child: SafeArea(
        top: false,
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Container(
              width: 36,
              height: 4,
              decoration: BoxDecoration(
                color: const Color(0xFFEDEDF2),
                borderRadius: BorderRadius.circular(AppConstants.pillRadius),
              ),
            ),
            const SizedBox(height: 16),
            Text(
              'Profile QR',
              style: AppTextStyles.heading3.copyWith(
                fontSize: 14.5,
                fontWeight: FontWeight.w700,
              ),
            ),
            const SizedBox(height: 4),
            Text(
              'Scan to view this profile',
              style: AppTextStyles.caption.copyWith(fontSize: 12),
            ),
            const SizedBox(height: 16),
            _QrImage(shareUrl: shareUrl),
            const SizedBox(height: 16),
            ProfileLinkBox(shareUrl: shareUrl),
            const SizedBox(height: 14),
            Row(
              children: [
                Expanded(
                  child: ShareActionButton(
                    icon: Icons.copy_rounded,
                    label: 'Copy Link',
                    filled: false,
                    onTap: () => copyProfileLink(context, shareUrl),
                  ),
                ),
                const SizedBox(width: 10),
                Expanded(
                  child: ShareActionButton(
                    icon: Icons.ios_share_rounded,
                    label: 'Share',
                    filled: true,
                    onTap: () {
                      Navigator.of(context).pop();
                      Share.share(shareUrl, subject: '$name on PropCid');
                    },
                  ),
                ),
              ],
            ),
          ],
        ),
      ),
    );
  }
}

class _QrImage extends StatelessWidget {
  final String shareUrl;

  const _QrImage({required this.shareUrl});

  static const double _kSize = 220;

  @override
  Widget build(BuildContext context) {
    return Container(
      padding: const EdgeInsets.all(14),
      decoration: BoxDecoration(
        color: AppColors.cardBackground,
        borderRadius: BorderRadius.circular(AppConstants.cardRadius),
        boxShadow: AppColors.surfaceCardShadow,
      ),
      child: SizedBox(
        width: _kSize,
        height: _kSize,
        child: CachedNetworkImage(
          imageUrl: profileQrImageUrl(shareUrl, size: 440),
          fit: BoxFit.contain,
          placeholder: (_, _) => const Center(
            child: SizedBox(
              width: 24,
              height: 24,
              child: CircularProgressIndicator(strokeWidth: 2),
            ),
          ),
          // The QR is generated by a remote service, so it needs a network
          // round-trip; an honest failure state beats a broken image box.
          errorWidget: (_, _, _) => Center(
            child: Column(
              mainAxisAlignment: MainAxisAlignment.center,
              children: [
                const Icon(
                  Icons.qr_code_2_rounded,
                  size: 40,
                  color: AppColors.textHint,
                ),
                const SizedBox(height: 8),
                Text(
                  "Couldn't load the QR code.\nUse Copy Link instead.",
                  textAlign: TextAlign.center,
                  style: AppTextStyles.caption.copyWith(fontSize: 11.5),
                ),
              ],
            ),
          ),
        ),
      ),
    );
  }
}
